src/routes/main.py
# This line of code is importing various modules and classes from different files and libraries.
from flask import Blueprint,flash,render_template,url_for,session,redirect,request,jsonify
from ..extensions import db
from ..models import *
from ..helper import *
from datetime import date
# The line `todays_date = date.today()` is assigning the current date to the variable `todays_date`.
# The `date.today()` function is a method from the `datetime` module that returns the current local
# date as a `date` object.
todays_date = date.today()
# 
# The line `main = Blueprint("main",__name__)` is creating a Blueprint object named "main".
main = Blueprint("main",__name__)

@main.route("/home",methods=["GET","POST"])
@main.route("/",methods=["GET","POST"])
def login():
    """
    The `login` function checks if a user has already voted, and if not, adds the user to the database
    and redirects them to the appropriate voting page based on their level.
    :return: The code is returning a redirect to different routes based on certain conditions. If the
    request method is "POST" and the student has already voted, it flashes a message "Already Voted!".
    If the student's level is "Higher" or "Senior", it adds the student to the database, sets session
    variables for rollNo and name, and redirects to the "main.splVote" route.
    """
    if request.method == "POST":
        session.permanent = True
        name,rollNo = request.form["studName"].title(),request.form["rollNo"]
        exists = db.session.query(db.session.query(Students).filter_by(rollNo=rollNo).exists()).scalar()
        if exists:
            flash("Aldready Voted!")
        elif getLevel(rollNo) == "Higher" or getLevel(rollNo) == "Senior":
            new_user = Students(rollNo=int(rollNo),name=str(name))
            db.session.add(new_user)
            session["rollNo"] = rollNo
            session["name"] = name
            return redirect(url_for("main.splVote"))
        elif getLevel(rollNo) == "Middle":
            new_user = Students(rollNo=int(rollNo),name=str(name))
            db.session.add(new_user)
            session["rollNo"] = rollNo
            session["name"] = name
            return redirect(url_for("main.asplMiddleVote"))
        else:
            return "<h1>You are trying to cheat 😡</h1>"
    return render_template("index.html",year=todays_date.year)

@main.route("/splVote",methods=["GET","POST"])
def splVote():
    """
    The function `splVote()` checks if a user is logged in, retrieves special data, and allows the user
    to vote, redirecting them to different URLs based on their level.
    :return: either a redirect to the login page or a rendered template "splVote.html" with the data
    variable passed to it.
    """
    splData = sendSPLData()
    if "rollNo" and "name" in session:
        rollNo = session["rollNo"]
        if db.session.query(db.session.query(Students).filter_by(rollNo=int(rollNo)).exists()).scalar():
            if request.method == "POST":
                if request.form.get('userVote') != None:
                    userVote = request.form.get('userVote')
                    try:
                        addVote = SplTable(rollNo=int(rollNo) , splName=userVote)
                        db.session.add(addVote)
                    except Exception as e:
                        flash(str(e))
                if getLevel(rollNo) == "Senior":
                    return jsonify({'url':"/asplSrSecVote"})
                else:
                    return jsonify({'url':"/asplHsecVote"})
    else:
        return redirect(url_for('main.login'))
    return render_template("splVote.html",data = splData)

@main.route("/asplMiddleVote",methods=["GET","POST"])
def asplMiddleVote():
    """
    The function `asplMiddleVote` allows a middle-level student to vote in the ASPL (Assistant School
    Prefects) election and stores their vote in the database.
    :return: either a JSON response with a URL to "/success" or a string "<h1>You are trying to cheat
    😡</h1>".
    """
    aspldata = sendASPLMiddleData()
    if "rollNo" and "name" in session:
        rollNo = session["rollNo"]
        if getLevel(rollNo) == "Middle":
            if db.session.query(db.session.query(Students).filter_by(rollNo=rollNo).exists()).scalar():
                if request.method == "POST":
                    if request.form.get('userVote') != None:
                        userVote = request.form.get('userVote')
                        try:
                            addVote = Aspl_Middle_Table(rollNo=rollNo , asplName=userVote)
                            db.session.add(addVote)
                        except:
                            flash("Internal server error")
                    return jsonify({'url':"/success"})
        else:
            return "<h1>You are trying to cheat 😡</h1>"
    else:
        return redirect(url_for("main.login"))
    return render_template("asplMiddleVote.html",data=aspldata)

@main.route("/asplHsecVote",methods=["GET","POST"])
def asplHsecVote():
    """
    The function `asplHsecVote` checks if the user is logged in and has the appropriate level of access,
    and then allows them to vote in the ASPL Higher Secondary election.
    :return: either a JSON response with a URL to "/success" or a rendered HTML template
    "asplHsecVote.html" with the data variable.
    """
    aspldata = sendASPLHsecData()
    if "rollNo" and "name" in session:
        rollNo = session["rollNo"]
        if getLevel(rollNo) == "Higher":
            if db.session.query(db.session.query(Students).filter_by(rollNo=rollNo).exists()).scalar():
                if request.method == "POST":
                    if request.form.get('userVote') != None:
                        userVote = request.form.get('userVote')
                        try:
                            addVote = Aspl_hSec_Table(rollNo=rollNo,asplName=userVote)
                            db.session.add(addVote)
                        except:
                            flash("Internal server error")
                    return jsonify({'url':"/success"})
        else:
            return "<h1>You are trying to cheat 😡</h1>"
    else:
        return redirect(url_for("main.login"))
    return render_template("asplHsecVote.html",data=aspldata)

@main.route("/asplSrSecVote",methods=["GET","POST"])
def asplSrSecVote():
    """
    The function `asplSrSecVote` handles the voting process for senior secondary students and checks for
    authentication and authorization before allowing the vote.
    :return: either a JSON response with a URL to "/success" or a string "<h1>You are trying to cheat
    😡</h1>".
    """
    aspldata = sendASPLSrSecData()
    if "rollNo" and "name" in session:
        rollNo = session["rollNo"]
        if getLevel(rollNo) == "Senior":
            if db.session.query(db.session.query(Students).filter_by(rollNo=rollNo).exists()).scalar():
                if request.method == "POST":
                    if request.form.get('userVote') != None:
                        userVote = request.form.get('userVote')
                        try:
                            addVote = Aspl_Sr_Sec_Table(rollNo=rollNo,asplName=userVote)
                            db.session.add(addVote)
                        except:
                            flash("Internal server error")
                    return jsonify({'url':"/success"})
        else:
            return "<h1>You are trying to cheat 😡</h1>"
    else:
        return redirect(url_for("main.login"))
    return render_template("asplSrSecVote.html",data=aspldata)


@main.route("/logout")
def logout():
    """
    The `logout` function clears the session and redirects the user to the login page.
    :return: a redirect to the login page.
    """
    [session.pop(key) for key in list(session.keys())]
    return redirect(url_for("main.login"))

@main.route("/success", methods=["GET","POST"])
def voteSuccess():
    """
    The function checks if the "name" and "rollNo" keys are present in the session dictionary, and if
    so, it returns a rendered template with the name variable passed to it, otherwise it redirects to
    the login page.
    :return: either the rendered template "success.html" with the variable "name" passed to it, or it is
    redirecting to the "login" route.
    """
    if "name" and "rollNo" in session:
        name = session["name"]
        return render_template("success.html",name=name)
    else:
        return redirect(url_for("main.login"))

src/templates/asplHsecVote.html
{% extends "base.html" %}

{% block title %}ASPL-VoteSection{% endblock %}

{% block customCSS %}
    <!-- Custom Css -->
    <link rel="stylesheet" href="{{url_for('static',filename='splVote.css')}}"">
{% endblock %}

{% block customJS %}
    <!-- Custom JS -->
    <script src="/static/voteForm.js"></script>
{% endblock %}

{% block bodyContent %}
    <h3 class="greet">Select the Assistant School Pupil Leader (ASPL) for your school</h3>
    
    {% for message in get_flashed_messages() %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}

    <div class="candiContainer shadow p-3">
        
      <h4 class="title">The candidates for the Assistant School Pupil Leader (ASPL) election are</h4>
        
        <form action="/asplVote" method="POST">
          <div class="row">
            {% for candidate in data %}
              <div class="col-sm-6">
                    <div class="card mb-3" style="max-width: 500px;">
                        <div class="row g-0">
                          <div class="col-md-4">
                            <img src="{{ url_for('static', filename='img/') }}/{{candidate[1]}}"
                            style="width: 150px; height: 150px;">
                          </div>
                          <div class="col-md-8">
                            <div class="card-body">
                              <h5 class="card-title">{{candidate[0]}}</h5>
                              <button type="button" id="VoteButton" value="{{candidate[0]}}" onclick="sendUserVote(this.value,'/asplHsecVote')" class="btn btn-primary">Vote for me</button>
                            </div>
                          </div>
                        </div>
                    </div>
              </div>
            {% endfor %}
            </div>
        </form>
    </div>
{% endblock %}

src/templates/asplMiddleVote.html
{% extends "base.html" %}

{% block title %}ASPL-VoteSection{% endblock %}

{% block customCSS %}
    <!-- Custom Css -->
    <link rel="stylesheet" href="{{url_for('static',filename='splVote.css')}}"">
{% endblock %}

{% block customJS %}
    <!-- Custom JS -->
    <script src="/static/voteForm.js"></script>
{% endblock %}

{% block bodyContent %}
    <h3 class="greet">Select the Assistant School Pupil Leader (ASPL) for your school</h3>
    
    {% for message in get_flashed_messages() %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}

    <div class="candiContainer shadow p-3">
        
      <h4 class="title">The candidates for the Assistant School Pupil Leader (ASPL) election are</h4>
        
        <!-- <form action="{{url_for('main.asplMiddleVote')}}" method="POST"> -->
            <div class="asplVoteForm">
              <div class="row">
              {% for candidate in data %}
                <div class="col-sm-6">
                      <div class="card mb-3" style="max-width: 500px;">
                          <div class="row g-0">
                            <div class="col-md-4">
                              <img src="{{ url_for('static', filename='img/') }}/{{candidate[1]}}"
                              style="width: 150px; height: 150px;">
                            </div>
                            <div class="col-md-8">
                              <div class="card-body">
                                <h5 class="card-title">{{candidate[0]}}</h5>
                                <button type="button" id="VoteButton" value="{{candidate[0]}}" onclick="sendUserVote(this.value,'/asplMiddleVote')" class="btn btn-primary">Vote for me</button>
                              </div>
                            </div>
                          </div>
                      </div>
                </div>
              {% endfor %}
              </div>
            </div>
        <!-- </form> -->
    </div>
{% endblock %}

src/templates/asplSrSecVote.html
{% extends "base.html" %}

{% block title %}ASPL-VoteSection{% endblock %}

{% block customCSS %}
    <!-- Custom Css -->
    <link rel="stylesheet" href="{{url_for('static',filename='splVote.css')}}">
{% endblock %}

{% block customJS %}
    <!-- Custom JS -->
    <script src="{{url_for('static',filename='voteForm.js')}}"></script>
{% endblock %}

{% block bodyContent %}
    <h3 class="greet">Select the Assistant School Pupil Leader (ASPL) for your school</h3>
    
    {% for message in get_flashed_messages() %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}

    <div class="candiContainer shadow p-3">
        
      <h4 class="title">The candidates for the Assistant School Pupil Leader (ASPL) election are</h4>
        
        <form action="{{url_for('main.asplSrSecVote')}}" method="POST">
            <div class="asplVoteForm">
              <!-- Row 1 -->
                <div class="row">
                {% for candidate in data %}
                  <div class="col-sm-6">
                        <div class="card mb-3" style="max-width: 500px;">
                            <div class="row g-0">
                              <div class="col-md-4">
                                <img src="{{ url_for('static', filename='img/') }}/{{candidate[1]}}"
                                style="width: 150px; height: 150px;">
                              </div>
                              <div class="col-md-8">
                                <div class="card-body">
                                  <h5 class="card-title">{{candidate[0]}}</h5>
                                  <button type="button" id="VoteButton" value="{{candidate[0]}}" onclick="sendUserVote(this.value,'/asplSrSecVote')" class="btn btn-primary">Vote for me</button>
                                </div>
                              </div>
                            </div>
                        </div>
                  </div>
                {% endfor %}
                </div>
            </div>
        </form>
    </div>
{% endblock %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% block customCSS %}{% endblock %}
    <!-- Style CSS -->
    <link rel="stylesheet" href="{{ url_for('static',filename='style.css') }}"> 
    <!-- BootStrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <!-- AJAX -->
    <script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
    <!-- BootStrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    {% block customJS %}{% endblock %}
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <header>
        <div class="schoolBanner">
        <img src="https://www.vvka.org.in/assets/img/logo.png" alt="logo" class="schoolLogo">
        <h2 class="schoolName">
        Smt. Kasturba Nimchand Shah P. Muthyalu Chetty Vivekananda Vidyalaya Junior College,Perambur,Chennai, 600 011<br>eElection Portal
        </h2>
        </div>
    </header>
    {% block bodyContent %}
    {% endblock %}
    {% block footer %}
    <footer>
        <p>&copy; 2023 Smt. Kasturba Nimchand Shah P. Muthyalu Chetty Vivekananda Vidyalaya Junior College</p>
    </footer>
    {% endblock %}
    
    
</body>
</html>

src/templates/index.html
{% extends "base.html" %}

{% block title %}SKNS-PMC-eElection{% endblock %}

{% block bodyContent %}
<h3 class="greet">Greetings from the SKNS PMC VV eElection <br> <br>{{year}}-{{year+1}}</h3>
    {% for message in get_flashed_messages() %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
<div class="loginBox shadow-lg p-3 mb-5 bg-body rounded">
    <h4 class="logintext">Vote For More Effective Management!</h4>
    <form action="/" method="POST">
        <div class="loginForm">
        <label for="studName" class="col-form-label">Your Name</label><br>
        <input type="text" name="studName" required aria-placeholder="studName" autocomplete="off" style="text-transform: capitalize;"><br>
        <label for="admissionNo" class="col-form-label">Your Roll No</label><br>
        <input type="number" name="rollNo" required aria-placeholder="rollNo" autocomplete="off"><br>
        </div>
        <button type="submit" class="btn btn-success">Login</button>
    </form>
</div>
{% endblock %}

src/templates/splVote.html
{% extends "base.html" %}

{% block title %}SPL-VoteSection{% endblock %}

{% block customCSS %}
    <!-- Custom Css -->
    <link rel="stylesheet" href="{{url_for('static',filename='splVote.css')}}">
{% endblock %}
{% block customJS %}
    <!-- Custom JS -->
    <script src="{{url_for('static',filename='voteForm.js')}}"></script>
{% endblock %}

{% block bodyContent %}

  <h3 class="greet">Select the School Pupil Leader (SPL) for your school</h3>
    
    {% for message in get_flashed_messages() %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}

    <div class="candiContainer shadow p-3">
      <form action="{{url_for('main.asplSrSecVote')}}" method="POST"></form>
      <h4 class="title">The candidates for the School Pupil Leader (SPL) election are</h4>
            <div class="splVoteForm">
              <div class="row">
                {% for candidate in data %}
                <div class="col-sm-6">
                      <div class="card mb-3" style="max-width: 500px;">
                          <div class="row g-0">
                            <div class="col-md-4">
                              <img src="{{ url_for('static', filename='img/') }}/{{candidate[1]}}"
                              style="width: 150px; height: 150px;">
                            </div>
                            <div class="col-md-8">
                              <div class="card-body">
                                <h5 class="card-title">{{candidate[0]}}</h5>
                                <button type="button" id="VoteButton" value="{{candidate[0]}}" onclick="sendUserVote(this.value,'/splVote')" class="btn btn-primary">Vote for me</button>
                              </div>
                            </div>
                          </div>
                      </div>
                </div>
                {% endfor %}
              </div>
      </form>
    </div>
{% endblock %}
{% block footer %}{% endblock %}

src/templates/success.html
{% extends "base.html" %}

{% block title %}Vote Sucess{% endblock %}

{% block bodyContent %}
<embed src="/static/beep.wav" loop="true" autostart="true" width="2" height="0">
<h1 style="text-align:center;margin:20px;"> 
    Hi, {{name}}
    <br>
    <br>
    <h1 style="text-align:center;margin:20px;">You have successfully voted in the election.</h1>
    <h1 style="text-align:center;margin:20px;">Click the refresh button below and move!</h1>

    <a href="{{url_for('main.logout')}}" class="btn btn-primary" style="width: 150px; margin: auto;">
        Refresh
    </a>
{% endblock %}